### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Kreijstal** [chaodreaming/Simple-LaTeX-OCR#1]
I know this was a lot of hard work, but how do you use it from the command line?

**Comment by Kreijstal** [comment]
i need to read

**Comment by Kreijstal** [comment]
But still consider adding example images with example outputs :), to README.md

**Comment by chaodreaming** [comment]
I just added the command line and changed the name, see readme.md for details

> 但仍可考虑添加带有示例输出的示例图像:)，以 README.md
