### ISSUE TITLE
OCR failure example

### ISSUE THREAD

**Issue by vertexi** [chaodreaming/Simple-LaTeX-OCR#2]
![test](https://github.com/chaodreaming/Simple-LaTeX-OCR/assets/22127472/b109b7aa-27f9-476f-b21a-2e7bd646c906)

result: 
$$
\left[\dot{i}_{d}\right]=\frac{2}{3}(\left[-\frac{Z}{L}\quad\omega\right]\left[i_{d}\right]+\left[\frac{V_{d c}}{L}\quad0\right]\left[D_{d}\right])
$$

![image](https://github.com/chaodreaming/Simple-LaTeX-OCR/assets/22127472/4a105c84-0a9f-4c59-9d78-ebd2b089cf0d)

**Comment by chaodreaming** [comment]
What scenario would bring up this picture

**Comment by vertexi** [comment]
I'm designing a controller, this is state space model of my system.

The picture is just latex equation which rendering in mathML using mathjax.

**Comment by vertexi** [comment]
The original latex equation in case you want to try it yourself.

```latex
$$
\begin{bmatrix} \dot{i}_d \\ \dot{i}_q \end{bmatrix} = \frac{2}{3}(\begin{bmatrix} -\frac{Z}{L} & \omega   \\   -\omega & -\frac{Z}{L} \end{bmatrix}   \begin{bmatrix} i_d \\ i_q \end{bmatrix}  + \begin{bmatrix} \frac{V_{dc}}{L} & 0   \\   0 & \frac{V_{dc}}{L} \end{bmatrix}  \begin{bmatrix} D_d \\ D_q \end{bmatrix})
$$
```

**Comment by chaodreaming** [comment]
Now that the original code of latex is known, why ocr and what is the purpose of bringing up this issue?

**Comment by vertexi** [comment]
No problem at all. I just want to know how good your model is. Hope gives some samples to improve your model.

If you have no interest in this issue. I just closed it. Thank you for your time.

**Comment by chaodreaming** [comment]
The initial idea was just for formula recognition in the document pdf category, without considering that type, so I'd like to understand the specific usage scenario, and if it's a real need, I'll consider updating the model next

**Comment by chaodreaming** [comment]
Although this model may not be that common, I still found some problems, when the size of the model varies a lot, the model becomes poor, next I will make a small scale model for trying to improve the problem, the reason why it is a small model is because I have limited computing power

**Comment by vertexi** [comment]
![test2](https://github.com/chaodreaming/Simple-LaTeX-OCR/assets/22127472/43d19f5d-cf73-4125-b9bd-47deb4c307f2)

This is a screenshot of an IEEE thesis's equation.

reuslt:

```latex
\left\{\begin{array}{l l}{\sum_{1}^{1,1}-\log(a_{i})-M=0}\\ {\sum_{i=1}^{1,1}\cos(a_{i})=0}\\ {\sum_{i=1}^{1,1}\cos(a_{i})=0}\\ {\cdots}\\ {\sum_{i=1}^{1,1}\cos(n a_{i})=0}\\ {\sum_{i=1}^{1,1}\cos(n a_{i})=0}\end{array}\right\}
92.16%
6,844ms
```

![image](https://github.com/chaodreaming/Simple-LaTeX-OCR/assets/22127472/8296039c-1ccc-487a-896a-a04655e8772a)

The scenario is sometimes I just want to copy some equation from other document which I don't have source code.

**Comment by vertexi** [comment]
Looks like you have got some good ideas. Keep going.

**Comment by chaodreaming** [comment]
Your question is very helpful to me, because on the whole dataset there is a large percentage of very short latex, which is the reason why training is difficult, after all, the 110 million dataset is just too big, so I will consider to reduce the portion of short latex, because this portion works very well

**Comment by chaodreaming** [comment]
Next I'm going to train a small model using transfer learning methods to try black and white reversal and larger scaling, and if that works, I'll next start training a larger model

**Comment by STEVENTAN100** [comment]
I think single-line formula recognition is doing almost perfect, but multi-line one such as matrix can apply with only simple cases.
So for the difficult one, I recommend just recognize it line by line.
